[tool.poetry]
name = "pytoshop"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
Cython = "^3.0.5"
numpy = "^1.26.2"

[build-system]
requires = ["setuptools", "cython"]
